# Choose a default "cargo run" tool.
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# probe-rs run is recommended if you have a debugger
runner = "probe-rs run --chip RP2040 --protocol swd --speed 16000"
# elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
# runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
